#!/usr/bin/env bash
# tenant-db-apply.sh - BOX-SIDE converge for the shared tenant Postgres
# (syd2; service via tenant-pg.sh). Runs as root over the CI-as-hands channel
# (workflow tenant-db-apply.yml) - syd2's inbound 22 answers CI only, so this
# never runs from a workstation. Idempotent; re-run prints OK lines.
#
# Always converges the BASELINE:
#   - PUBLIC may not connect to the postgres/swordfish admin DBs
#   - drill_canary database + a fixed marker row exist, so the restore drill
#     verifies CONTENT that provably came through dump->snapshot->restore
#
# With TENANT_SLUG set (password = FIRST LINE OF STDIN; never argv):
#   - role <slug>: LOGIN, no superuser/createdb/createrole; password re-asserted
#   - database <slug> owned by the role
#   - isolation both ways: PUBLIC revoked, only the role may connect
#   - verification: TCP auth as the role to its own DB succeeds; connecting
#     to drill_canary and swordfish DBs FAILS (delivery-green != content-true)

set -euo pipefail

CANARY_MARKER=swordfish-restore-drill-canary

cid=$(docker ps --filter name=tenant-pg --format '{{.ID}}' | head -n1)
[ -n "$cid" ] || { echo "FAIL: no container matching 'tenant-pg' - deploy tenant-pg.sh first"; exit 1; }

sql() { # $1 = database; SQL on stdin (rides the pipe, never argv)
    docker exec -i "$cid" psql -U swordfish -d "$1" -v ON_ERROR_STOP=1 -qtAX
}

# --- baseline: admin DBs closed to PUBLIC, canary present --------------------------
sql postgres <<'SQL'
REVOKE CONNECT ON DATABASE postgres  FROM PUBLIC;
REVOKE CONNECT ON DATABASE swordfish FROM PUBLIC;
SQL
echo "OK: PUBLIC revoked on admin DBs"

if [ "$(echo "SELECT 1 FROM pg_database WHERE datname='drill_canary'" | sql postgres)" != 1 ]; then
    echo 'CREATE DATABASE drill_canary' | sql postgres
    echo "CHANGED: drill_canary database created"
fi
echo 'REVOKE CONNECT ON DATABASE drill_canary FROM PUBLIC' | sql postgres
sql drill_canary <<SQL
CREATE TABLE IF NOT EXISTS drill_marker (k text PRIMARY KEY, stamped_at timestamptz NOT NULL DEFAULT now());
INSERT INTO drill_marker (k) VALUES ('$CANARY_MARKER') ON CONFLICT DO NOTHING;
SQL
[ "$(echo "SELECT k FROM drill_marker WHERE k='$CANARY_MARKER'" | sql drill_canary)" = "$CANARY_MARKER" ] \
    || { echo "FAIL: canary marker did not read back"; exit 1; }
echo "OK: drill canary present (marker read back)"

# --- tenant (optional) --------------------------------------------------------------
if [ -n "${TENANT_SLUG:-}" ]; then
    slug=$TENANT_SLUG
    [[ "$slug" =~ ^[a-z][a-z0-9_]{1,30}$ ]] \
        || { echo "FAIL: slug '$slug' must match ^[a-z][a-z0-9_]{1,30}\$"; exit 1; }
    IFS= read -r PW
    [ -n "$PW" ] || { echo "FAIL: no password on stdin"; exit 1; }
    # generated by tenant-db.sh as token_urlsafe: quoting-safe by construction,
    # and enforced here so the inlined SQL literal below can never break out
    [[ "$PW" =~ ^[A-Za-z0-9_-]+$ ]] || { echo "FAIL: password outside the [A-Za-z0-9_-] charset"; exit 1; }

    if [ "$(echo "SELECT 1 FROM pg_roles WHERE rolname='$slug'" | sql postgres)" = 1 ]; then
        echo "ALTER ROLE \"$slug\" WITH LOGIN PASSWORD '$PW' NOSUPERUSER NOCREATEDB NOCREATEROLE" | sql postgres
        echo "OK: role $slug exists (password + attributes re-asserted)"
    else
        echo "CREATE ROLE \"$slug\" WITH LOGIN PASSWORD '$PW' NOSUPERUSER NOCREATEDB NOCREATEROLE" | sql postgres
        echo "CHANGED: role $slug created"
    fi

    if [ "$(echo "SELECT 1 FROM pg_database WHERE datname='$slug'" | sql postgres)" != 1 ]; then
        echo "CREATE DATABASE \"$slug\" OWNER \"$slug\"" | sql postgres
        echo "CHANGED: database $slug created"
    fi
    sql postgres <<SQL
REVOKE CONNECT ON DATABASE "$slug" FROM PUBLIC;
GRANT  CONNECT ON DATABASE "$slug" TO "$slug";
SQL
    echo "OK: database $slug closed to PUBLIC, open to its role"

    # verification from the ROLE's point of view, over TCP (forces password auth;
    # the password rides stdin into the container shell, never argv)
    as_tenant() { # $1 = database -> exit code of a select 1
        docker exec -i "$cid" bash -c \
            'IFS= read -r PGPASSWORD; export PGPASSWORD; exec psql -h 127.0.0.1 -U "$1" -d "$2" -qtAX -c "SELECT 1"' \
            _ "$slug" "$1" <<<"$PW"
    }
    [ "$(as_tenant "$slug")" = 1 ] || { echo "FAIL: $slug cannot reach its own DB over TCP"; exit 1; }
    echo "OK: $slug connects to its own DB (TCP, password auth)"
    if as_tenant drill_canary >/dev/null 2>&1; then
        echo "FAIL: $slug can connect to drill_canary - isolation broken"; exit 1
    fi
    if as_tenant swordfish >/dev/null 2>&1; then
        echo "FAIL: $slug can connect to the swordfish admin DB - isolation broken"; exit 1
    fi
    echo "OK: isolation verified ($slug rejected by drill_canary + swordfish)"
    echo "== converged: baseline + tenant $slug"
else
    echo "== converged: baseline (no tenant requested)"
fi
